version: '3.8'

services:
  nginx: 
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - web
    depends_on:
      - frontend1
      - api1

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart:  unless-stopped
    networks: 
      - web

  # ========== APPS DE EJEMPLO ==========

  portafolio:
    build:  ../apps/portafolio
    container_name: portafolio
    restart: unless-stopped
    networks:
      - web
  
  # React App
  frontend1:
    build:  ../apps/frontend1
    container_name: frontend1
    restart: unless-stopped
    networks:
      - web
    environment:
      - NODE_ENV=production

  # API FastAPI
  api1:
    build: ../apps/api1
    container_name: api1
    restart: unless-stopped
    networks:
      - web
    environment:
      - PYTHONUNBUFFERED=1

networks:
  web:
    driver: bridge

